### ISSUE TITLE
PEP8: Use `is`, not == when comparing to the singletons: True, False, and None

### ISSUE THREAD

**Issue by cclauss** [pass-culture/pass-culture-api#2734]
[PEP8 recommends](https://www.python.org/dev/peps/pep-0008/#programming-recommendations) using `Offer.isActive is True` instead of using `Offer.isActive == True` because  [`is` cannot be overloaded but `==` can be](https://stackoverflow.com/questions/23985501/expressing-is-not-null-without-causing-a-pep8-error) by [`__eq__`methods in this codebase](https://github.com/pass-culture/pass-culture-api/search?q=__eq__) or its dependencies.

% `flake8 --count --select=E711,E712 --show-source --statistics`
```
./tests/repository/offer_queries_test.py:77:37: E711 comparison to None should be 'if cond is None:'
            .filter((Stock.quantity == None) | ((Stock.quantity - func.coalesce(bookings_quantity.c.quantity, 0)) > 0))
                                    ^

[ ... ]

./src/pcapi/routes/native/v1/favorites.py:38:24: E712 comparison to True should be 'if cond is True:' or 'if cond:'
        Offer.isActive == True,
                       ^
43    E711 comparison to None should be 'if cond is not None:'
65    E712 comparison to True should be 'if cond is True:' or 'if cond:'
108
```

**Comment by dbaty** [comment]
Hi. Thanks for this report. Actually, we have disabled a pylint check until we change that to `Stock.quantity.is_(None)` which is better form. It's planned and will be done, some day.
